### ISSUE TITLE
编译报错这个提示怎么解决VS2022

### ISSUE THREAD

**Issue by 43317535** [SlimeNull/OpenGptChat#9]
![image](https://user-images.githubusercontent.com/58316822/228417099-d7204cd9-7caf-43c3-93ab-c6f77afd9dc0.png)

**Comment by SlimeNull** [comment]
不知道. 我这边也是 VS2022, 没出现这种情况.

**Comment by SlimeNull** [comment]
如果你只是想使用, 那么不需要手动编译, 直接在 Releases 中下载最新版本就好了, 更新会比较频繁的
